spring:
  application:
    name: hello-spring-cloud-ribbon
server:
  port: 16007
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver2:16001/eureka/,http://eurekaserver1:16000/eureka/,http://eurekaserver3:16002/eureka/
