eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver2:16001/eureka/,http://eurekaserver1:16000/eureka/,http://eurekaserver3:16002/eureka/
spring:
  application:
    name: hello-spring-cloud-eureka-member
  zipkin:
    base-url: http://localhost:16009
server:
  port: 16003
