server:
  port: 16000
eureka:
    instance:
      ###不能使用localhost
      hostname: eurekaserver1
    client:
      #### eureka中需要将下面两个设置为true 才能注册为可用 register-with-eureka 注册实例
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://eurekaserver2:16001/eureka/,http://eurekaserver1:16000/eureka/,http://eurekaserver3:16002/eureka/