spring:
  application:
    name: hello-spring-cloud-zipkin
server:
  port: 16009
eureka:
    client:
      service-url:
        defaultZone: http://eurekaserver1:16000/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
