spring:
  application:
    name: hello-spring-cloud-zipkin
  sleuth:
    enabled: false
  rabbitmq:
    host: 192.168.1.131
    port: 5672
    username: guest
    password: guest
server:
  port: 16009

eureka:
    client:
      service-url:
        defaultZone: http://eurekaserver1:16000/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
